// <auto-generated />

#nullable enable

namespace Serene.MovieDB;

/// <summary>An attribute that sets the editor type to <c>Serene.MovieDB.MovieCastEditor</c> and its options.</summary>
public partial class MovieCastEditorAttribute : CustomEditorAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serene.MovieDB.MovieCastEditor";

    /// <summary>Creates a new instance of the <c>MovieCastEditorAttribute</c> class.</summary>
    public MovieCastEditorAttribute()
        : base(Key)
    {
    }
}