// <auto-generated />

#nullable enable

namespace Serene.MovieDB;

/// <summary>An attribute that sets the formatter type to <c>Serene.MovieDB.GenreListFormatter</c> and its options.</summary>
public partial class GenreListFormatterAttribute : CustomFormatterAttribute
{
    /// <summary>The formatter type key.</summary>
    public const string Key = "Serene.MovieDB.GenreListFormatter";

    /// <summary>Creates a new instance of the <c>GenreListFormatterAttribute</c> class.</summary>
    public GenreListFormatterAttribute()
        : base(Key)
    {
    }
}